title: My site
subtitle: Just some words
author: George Washington
description: >
  Here is my website. This description will appear in the meta
  data on the site and in the feed.xml site description.

# git edit capabilities
remote_theme: jasongaylord/SpaacedOut
git:
#  host: https://github.com/
  repository: jasongaylord/SpaacedOut
  branch: gh-pages

# pagination and permalink
show_excerpts: true
paginate: 5
page_group_size: 5
paginate_path: "/blog/page/:num"
permalink: /blog/:year/:month/:day/:title

# content expansion
content:
  head-s: false
#  header-s: false
# Since GitHub Pages targets Jekyll 3.8 and not Jekyll 4, we are limited on loading includes in
# dynamically. Hopefully they change it in the future. So, the commented out blocks below are 
# for future usage. Since they'll never be true, the Jekyll processor will skip these. If
# and when these are allowed, I'll post in the Theme README how to safely "upgrade."
#  head-suffix: head-suffix.html  
#  header-suffix: header-suffix.html

# contact
contact: 
#  avatar-image: /assets/images/avatar.png
#  email: email@gmail.com # Uncomment if you want feedback via email (it will expose your email)
#  url: https://domain.com/contact.html # Uncomment if you want to provide a contact form

# social links (uncomment the links you'd like to include and)
social:
#  facebook: jekyll
#  github: jekyll
#  instagram: jekyll
#  linkedin: jekyll
#  pinterest: jekyll
#  stackoverflow: "11111"
#  twitter: jekyllrb
#  youtube: jekyll

#  google_analytics: UA-NNNNNNNN-N

rss: rss
# The site generates a feed at /feed.xml. Uncomment below to override
# feed:
#   path: /myfeed.xml

# comments
comments:
#  enabled: false
#  show_count: false
#  disqus_shortname: jekyll

# front matter
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
      comments: false
  -
    scope:
      path: "assets/pages"
      type: "pages"
    values:
      layout: page
      comments: false

#Kramdown Configuration      
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap